@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package lq2007.mcmod.isaacformc.common.capability;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;