@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package lq2007.mcmod.isaacmod.register.registers;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;